---
- hosts: app
  gather_facts: yes
  become: yes
  tasks:   
    - name: USERS | Add users with password, home folders
      ansible.builtin.user:
        name: "{{ item.key }}"
        comment: "{{ item.value.email }} | {{ item.value.name }} | {{ item.value.telephone }}"
        password: "{{ item.value.password | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/bash
        home: "/home/{{ item.key }}"
        append: yes
      loop: "{{ lookup('dict', users) }}"
